---
ansible_ssh_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/sandbox

# Necessary Variables for creating/provisioning the EC2 Instance
instance_type: g2.2xlarge
security_group: brainiac # Change the security group name here
# image: ami-34126654 # hvm
image: ami-06116566 # hvm-ssd
region: us-west-1 # Change the Region
keypair: sandbox # Change the keypair name
count: 1
