---

- name: Install dependecies
  apt: pkg={{ item }} state=present
  with_items:
    - pkg-config
    - zip
    - g++
    - zlib1g-dev
  sudo: yes

- name: Download the Bazel Installer
  get_url: url=https://github.com/bazelbuild/bazel/releases/download/0.1.4/bazel-0.1.4-installer-linux-x86_64.sh dest=/mnt/brainiac mode=0755

- name: Install Bazel
  shell: "/mnt/brainiac/bazel-0.1.4-installer-linux-x86_64.sh --bin=/mnt/brainiac/bin --base=/mnt/brainiac/.bazel --bazelrc=/mnt/brainiac/.bazelrc && touch /home/ubuntu/.ansible-bazel-installed"
  args:
    creates: /home/ubuntu/.ansible-bazel-installed
