---

- name: Update and Upgrade
  apt: update_cache=yes upgrade=safe
  sudo: yes

- name: Install development dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - g++
    - gfortran
    - git
    - libatlas-base-dev
    - libblas-dev
    - libfreetype6-dev
    - liblapack-dev
    - libncurses-dev
    - libopenblas-dev
    - libxft-dev
    - linux-headers-generic
    - linux-image-extra-virtual
    - pkg-config
    - python-dev
    - python-matplotlib
    - python-numpy
    - python-pandas
    - python-pip
    - python-pydot
    - python-sklearn
    - swig
    - unzip
    - unzip
    - wget
    - zip
    - zlib1g-dev
  sudo: yes

- name: Download the CUDA framework
  get_url: url=http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1410/x86_64/cuda-repo-ubuntu1410_7.0-28_amd64.deb dest=/home/ubuntu

- name: Install the CUDA deb file
  apt: deb=/home/ubuntu/cuda-repo-ubuntu1410_7.0-28_amd64.deb state=present
  sudo: yes

- name: Install CUDA package
  apt: pkg=cuda state=present update_cache=yes
  sudo: yes
  register: cuda

- lineinfile: dest="~/.bashrc" line="export CUDA_HOME=/usr/local/cuda"
- lineinfile: dest="~/.bashrc" line="export CUDA_ROOT=/usr/local/cuda"
- lineinfile: dest="~/.bashrc" line="export PATH=$PATH:$CUDA_ROOT/bin"
- lineinfile: dest="~/.bashrc" line="export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CUDA_ROOT/lib64"

- name: Restart
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
  sudo: yes
  when: cuda.changed
  register: reboot
  # when: "'Reboot' in cuda.stdout"

# - name: Waiting for server to restart
#   local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
#   sudo: false
#   register: reboot|!skipped
