---

- name: Update and Upgrade
  apt: update_cache=yes upgrade=safe
  sudo: yes

- name: Install development dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - g++
    - gfortran
    - git
    - libatlas-base-dev
    - libblas-dev
    - libfreetype6-dev
    - liblapack-dev
    - libncurses-dev
    - libopenblas-dev
    - libxft-dev
    - linux-headers-generic
    - linux-image-extra-virtual
    - pkg-config
    - python-dev
    - python-matplotlib
    - python-numpy
    - python-pandas
    - python-pip
    - python-pydot
    - python-sklearn
    - swig
    - unzip
    - unzip
    - wget
    - zip
    - zlib1g-dev
  sudo: yes

- name: Download the CUDA framework
  get_url: url=http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1410/x86_64/cuda-repo-ubuntu1410_7.0-28_amd64.deb dest=/home/ubuntu

- name: Install the CUDA deb file
  apt: deb=/home/ubuntu/cuda-repo-ubuntu1410_7.0-28_amd64.deb state=present
  sudo: yes

- name: Install CUDA package
  apt: pkg=cuda state=present update_cache=yes
  sudo: yes
  register: cuda

- name: Unarchive cuDNN
  unarchive: src=cudnn-6.5-linux-x64-v2.tgz dest=/home/ubuntu owner=ubuntu group=ubuntu mode=0755
  args:
    creates: /home/ubuntu/cudnn-6.5-linux-x64-v2

- name: Copy cuDNN
  shell:  cp -R /home/ubuntu/cudnn-6.5-linux-x64-v2/lib* /usr/local/cuda/lib64/
  sudo: yes
  args:
    creates: /usr/local/cuda/lib64/libcudnn_static.a

- name: Copy cuDNN Headers
  command:  cp -R /home/ubuntu/cudnn-6.5-linux-x64-v2/cudnn.h /usr/local/cuda/include/
  sudo: yes
  args:
    creates: /usr/local/cuda/include/cudnn.h

- lineinfile: dest="~/.bashrc" line="export CUDA_HOME=/usr/local/cuda"
- lineinfile: dest="~/.bashrc" line="export CUDA_ROOT=/usr/local/cuda"
- lineinfile: dest="~/.bashrc" line="export PATH=$PATH:$CUDA_ROOT/bin"
- lineinfile: dest="~/.bashrc" line="export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CUDA_ROOT/lib64"

- name: Restart
  command: reboot
  sudo: yes
  when: "'Reboot' in cuda.stdout"

- name: Wait for SSH to come up
  local_action: wait_for
                host={{ item.public_ip }}
                port=22
                state=started
  with_items: ec2.instances
